# Generated by Django 5.0.6 on 2024-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timing', models.TimeField()),
                ('Available', models.CharField(max_length=255)),
                ('Rooms', models.BooleanField(default=False)),
                ('session', models.CharField(max_length=255)),
            ],
        ),
    ]
