# Generated by Django 5.0.6 on 2024-07-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Timing',
            field=models.TimeField(null=True),
        ),
    ]
