# Generated by Django 4.2.9 on 2024-07-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproj', '0003_alter_hospital_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.PositiveIntegerField(max_length=255, null=True)),
                ('Gender', models.BooleanField(default=False, null=True)),
                ('Contact', models.CharField(max_length=255, null=True)),
                ('AppointmentDate', models.DateField(null=True)),
                ('AppointmentTime', models.TimeField(null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=255)),
                ('DoctorFee', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
