# Generated by Django 4.2.9 on 2024-07-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproj', '0005_doctor_user_alter_doctor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
