# Generated by Django 5.0.6 on 2024-07-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproj', '0006_alter_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffId', models.PositiveIntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.PositiveIntegerField()),
                ('Gender', models.BooleanField(default=False)),
                ('ShifTime', models.TimeField()),
                ('ShiftName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('Remarks', models.TextField()),
                ('Doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finalproj.doctor')),
            ],
        ),
    ]
