# Generated by Django 4.2.9 on 2024-07-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalproj', '0007_alter_doctor_photo_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialist',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Age', models.PositiveIntegerField()),
                ('Gender', models.CharField(max_length=100, null=True)),
                ('Contact', models.CharField(max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=255)),
                ('symptoms', models.CharField(max_length=255)),
                ('medicalcertifcate', models.BooleanField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('Address', models.TextField(max_length=255)),
                ('Doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finalproj.doctor')),
            ],
        ),
    ]
