# Generated by Django 5.0 on 2024-07-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproj', '0009_rename_email_patient_email_alter_doctor_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Remarks',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
