# Generated by Django 5.0 on 2024-07-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproj', '0010_alter_staff_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
