# Generated by Django 5.0 on 2024-07-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproj', '0011_alter_patient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medicalcertifcate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
