# Generated by Django 4.2.7 on 2024-07-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproj', '0012_alter_patient_medicalcertifcate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
